// automatically generated by the FlatBuffers compiler, do not modify

package com.supercell.swf;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FBColorTransform extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FBColorTransform __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int r() { return bb.get(bb_pos + 0) & 0xFF; }
  public void mutateR(int r) { bb.put(bb_pos + 0, (byte) r); }
  public int g() { return bb.get(bb_pos + 1) & 0xFF; }
  public void mutateG(int g) { bb.put(bb_pos + 1, (byte) g); }
  public int b() { return bb.get(bb_pos + 2) & 0xFF; }
  public void mutateB(int b) { bb.put(bb_pos + 2, (byte) b); }
  public int a() { return bb.get(bb_pos + 3) & 0xFF; }
  public void mutateA(int a) { bb.put(bb_pos + 3, (byte) a); }
  public int ra() { return bb.get(bb_pos + 4) & 0xFF; }
  public void mutateRa(int ra) { bb.put(bb_pos + 4, (byte) ra); }
  public int ga() { return bb.get(bb_pos + 5) & 0xFF; }
  public void mutateGa(int ga) { bb.put(bb_pos + 5, (byte) ga); }
  public int ba() { return bb.get(bb_pos + 6) & 0xFF; }
  public void mutateBa(int ba) { bb.put(bb_pos + 6, (byte) ba); }

  public static int createFBColorTransform(FlatBufferBuilder builder, int r, int g, int b, int a, int ra, int ga, int ba) {
    builder.prep(1, 7);
    builder.putByte((byte) ba);
    builder.putByte((byte) ga);
    builder.putByte((byte) ra);
    builder.putByte((byte) a);
    builder.putByte((byte) b);
    builder.putByte((byte) g);
    builder.putByte((byte) r);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FBColorTransform get(int j) { return get(new FBColorTransform(), j); }
    public FBColorTransform get(FBColorTransform obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

