// automatically generated by the FlatBuffers compiler, do not modify

package com.supercell.swf;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FBMovieClipFrame extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FBMovieClipFrame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int frameElementCount() { return bb.getInt(bb_pos + 0); }
  public void mutateFrameElementCount(int frame_element_count) { bb.putInt(bb_pos + 0, frame_element_count); }
  public int labelRefId() { return bb.getInt(bb_pos + 4); }
  public void mutateLabelRefId(int label_ref_id) { bb.putInt(bb_pos + 4, label_ref_id); }

  public static int createFBMovieClipFrame(FlatBufferBuilder builder, int frameElementCount, int labelRefId) {
    builder.prep(4, 8);
    builder.putInt(labelRefId);
    builder.putInt(frameElementCount);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FBMovieClipFrame get(int j) { return get(new FBMovieClipFrame(), j); }
    public FBMovieClipFrame get(FBMovieClipFrame obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

