// automatically generated by the FlatBuffers compiler, do not modify

package com.supercell.swf;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FBShortMatrix2x3 extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FBShortMatrix2x3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short a() { return bb.getShort(bb_pos + 0); }
  public void mutateA(short a) { bb.putShort(bb_pos + 0, a); }
  public short b() { return bb.getShort(bb_pos + 2); }
  public void mutateB(short b) { bb.putShort(bb_pos + 2, b); }
  public short c() { return bb.getShort(bb_pos + 4); }
  public void mutateC(short c) { bb.putShort(bb_pos + 4, c); }
  public short d() { return bb.getShort(bb_pos + 6); }
  public void mutateD(short d) { bb.putShort(bb_pos + 6, d); }
  public short x() { return bb.getShort(bb_pos + 8); }
  public void mutateX(short x) { bb.putShort(bb_pos + 8, x); }
  public short y() { return bb.getShort(bb_pos + 10); }
  public void mutateY(short y) { bb.putShort(bb_pos + 10, y); }

  public static int createFBShortMatrix2x3(FlatBufferBuilder builder, short a, short b, short c, short d, short x, short y) {
    builder.prep(2, 12);
    builder.putShort(y);
    builder.putShort(x);
    builder.putShort(d);
    builder.putShort(c);
    builder.putShort(b);
    builder.putShort(a);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FBShortMatrix2x3 get(int j) { return get(new FBShortMatrix2x3(), j); }
    public FBShortMatrix2x3 get(FBShortMatrix2x3 obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

