// automatically generated by the FlatBuffers compiler, do not modify

package com.supercell.swf;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FBShapeDrawBitmapCommand extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FBShapeDrawBitmapCommand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int unknown0() { return bb.getInt(bb_pos + 0); }
  public void mutateUnknown0(int unknown0) { bb.putInt(bb_pos + 0, unknown0); }
  public int textureIndex() { return bb.getInt(bb_pos + 4); }
  public void mutateTextureIndex(int texture_index) { bb.putInt(bb_pos + 4, texture_index); }
  public int pointCount() { return bb.getInt(bb_pos + 8); }
  public void mutatePointCount(int point_count) { bb.putInt(bb_pos + 8, point_count); }
  public int startingPointIndex() { return bb.getInt(bb_pos + 12); }
  public void mutateStartingPointIndex(int starting_point_index) { bb.putInt(bb_pos + 12, starting_point_index); }

  public static int createFBShapeDrawBitmapCommand(FlatBufferBuilder builder, int unknown0, int textureIndex, int pointCount, int startingPointIndex) {
    builder.prep(4, 16);
    builder.putInt(startingPointIndex);
    builder.putInt(pointCount);
    builder.putInt(textureIndex);
    builder.putInt(unknown0);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FBShapeDrawBitmapCommand get(int j) { return get(new FBShapeDrawBitmapCommand(), j); }
    public FBShapeDrawBitmapCommand get(FBShapeDrawBitmapCommand obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

