// automatically generated by the FlatBuffers compiler, do not modify

package com.supercell.swf;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FBTextField extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FBTextField __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int id() { return bb.getShort(bb_pos + 0) & 0xFFFF; }
  public void mutateId(int id) { bb.putShort(bb_pos + 0, (short) id); }
  public int unused0() { return bb.getShort(bb_pos + 2) & 0xFFFF; }
  public void mutateUnused0(int unused0) { bb.putShort(bb_pos + 2, (short) unused0); }
  public int fontNameRefId() { return bb.getInt(bb_pos + 4); }
  public void mutateFontNameRefId(int font_name_ref_id) { bb.putInt(bb_pos + 4, font_name_ref_id); }
  public short left() { return bb.getShort(bb_pos + 8); }
  public void mutateLeft(short left) { bb.putShort(bb_pos + 8, left); }
  public short top() { return bb.getShort(bb_pos + 10); }
  public void mutateTop(short top) { bb.putShort(bb_pos + 10, top); }
  public short right() { return bb.getShort(bb_pos + 12); }
  public void mutateRight(short right) { bb.putShort(bb_pos + 12, right); }
  public short bottom() { return bb.getShort(bb_pos + 14); }
  public void mutateBottom(short bottom) { bb.putShort(bb_pos + 14, bottom); }
  public int color() { return bb.getInt(bb_pos + 16); }
  public void mutateColor(int color) { bb.putInt(bb_pos + 16, color); }
  public int outlineColor() { return bb.getInt(bb_pos + 20); }
  public void mutateOutlineColor(int outline_color) { bb.putInt(bb_pos + 20, outline_color); }
  public int defaultTextRefId() { return bb.getInt(bb_pos + 24); }
  public void mutateDefaultTextRefId(int default_text_ref_id) { bb.putInt(bb_pos + 24, default_text_ref_id); }
  public int anotherTextRefId() { return bb.getInt(bb_pos + 28); }
  public void mutateAnotherTextRefId(int another_text_ref_id) { bb.putInt(bb_pos + 28, another_text_ref_id); }
  public int styles() { return bb.get(bb_pos + 32) & 0xFF; }
  public void mutateStyles(int styles) { bb.put(bb_pos + 32, (byte) styles); }
  public int align() { return bb.get(bb_pos + 33) & 0xFF; }
  public void mutateAlign(int align) { bb.put(bb_pos + 33, (byte) align); }
  public int fontSize() { return bb.get(bb_pos + 34) & 0xFF; }
  public void mutateFontSize(int font_size) { bb.put(bb_pos + 34, (byte) font_size); }
  public int unused1() { return bb.get(bb_pos + 35) & 0xFF; }
  public void mutateUnused1(int unused1) { bb.put(bb_pos + 35, (byte) unused1); }
  public int unused2() { return bb.getInt(bb_pos + 36); }
  public void mutateUnused2(int unused2) { bb.putInt(bb_pos + 36, unused2); }

  public static int createFBTextField(FlatBufferBuilder builder, int id, int unused0, int fontNameRefId, short left, short top, short right, short bottom, int color, int outlineColor, int defaultTextRefId, int anotherTextRefId, int styles, int align, int fontSize, int unused1, int unused2) {
    builder.prep(4, 40);
    builder.putInt(unused2);
    builder.putByte((byte) unused1);
    builder.putByte((byte) fontSize);
    builder.putByte((byte) align);
    builder.putByte((byte) styles);
    builder.putInt(anotherTextRefId);
    builder.putInt(defaultTextRefId);
    builder.putInt(outlineColor);
    builder.putInt(color);
    builder.putShort(bottom);
    builder.putShort(right);
    builder.putShort(top);
    builder.putShort(left);
    builder.putInt(fontNameRefId);
    builder.putShort((short) unused0);
    builder.putShort((short) id);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FBTextField get(int j) { return get(new FBTextField(), j); }
    public FBTextField get(FBTextField obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

